# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_course_url_course_modules_last_scraped_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="ai_draft_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="ai_draft_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="ai_draft_model",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="course",
            name="ai_draft_modules",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="course",
            name="ai_draft_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="course",
            name="ai_draft_source",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="course",
            name="ai_draft_years",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
