# Generated by Django 6.0.2 on 2026-02-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_ai_draft_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[("draft", "Draft"), ("confirmed", "Confirmed")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_records",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "unique_together": {("course", "title")},
            },
        ),
    ]
